### ISSUE TITLE
jsconfig.json: Property "plugins" is not allowed

### ISSUE THREAD

**Issue by codepunkt** [Microsoft/typescript-styled-plugin#8] opened 2017-09-29 06:29 UTC
Thanks the work you've put into this! `styled-components` intellisense would be awesome!

Unfortunately, i can't seem to get it to work using vscode 1.16.1. i've set it up according to the docs, but there is no intellisense available. Additionally, the jsconfig.json looks like this:

![plugins_not_allowed](https://user-images.githubusercontent.com/603683/31003503-51531176-a4f0-11e7-964e-5b810f06d33c.PNG)

**Comment by lyyourc** [comment] 2017-09-29 15:08
Is it a duplicate of #4 ?

**Comment by mjbvz** [comment] 2017-09-29 18:05
Should be addressed by https://github.com/SchemaStore/schemastore/pull/348

**Comment by mjbvz** [comment] 2017-09-29 18:11
The warning in the jsconfig should not stop the plugin from being loaded.

If you are not seeing the plugin being loaded after adding it to your `jsconfg.json`, please make sure you are using a workspace version of TypeScript. Run the `Select TypeScript version` command in VS Code to check this:

<img width="606" alt="screen shot 2017-09-29 at 11 07 18 am" src="https://user-images.githubusercontent.com/12821956/31029438-9170c30a-a506-11e7-9738-19d7a60288ff.png">

Plugins also require TypeScript 2.3+.

After updating your `jsconfig.json` the first time, make sure to restart TypeScript so that it gets loaded using the `Restart TS server` command or by reloading the VS Code window

@codepunkt Please let me know if those steps work

**Comment by lyyourc** [comment] 2017-09-30 00:48
It doesn't work :(
I have `Select TypeScript version` , and `Restart TS server` , and try to restart VS Code~


![image](https://user-images.githubusercontent.com/6823863/31040606-e5e12bf8-a54e-11e7-833e-21704ec2f2f2.png)


<details>
<summary> jsconfig.json </summary>

```js
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "styled",
          "sty"
        ]
      }
    ]
  }
}
```
</details>

<details>
<summary> settings.json </summary>

```js
{
  "prettier.semi": false,
  "prettier.trailingComma": "es5",
  "prettier.singleQuote": true,
  "prettier.jsxBracketSameLine": true,

  "emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html"
  },
  "emmet.syntaxProfiles": {
    "javascript": "jsx"
  },

  "path-autocomplete.pathMappings": {
    "/": "${workspace}",
    "@": "${workspace}/src"
  },
  "typescript.tsdk": "node_modules/typescript/lib"
}

```
</details>

<details>
<summary> package.json </summary>

  ```js
{
  "dependencies": {
    "gatsby": "^1.8.11",
    "gatsby-link": "^1.4.1",
    "gatsby-plugin-feed": "^1.3.9",
    "gatsby-plugin-google-analytics": "^1.0.7",
    "gatsby-plugin-manifest": "^1.0.8",
    "gatsby-plugin-nprogress": "^1.0.7",
    "gatsby-plugin-offline": "^1.0.9",
    "gatsby-plugin-react-helmet": "^1.0.6",
    "gatsby-plugin-styled-components": "^1.0.5",
    "gatsby-remark-autolink-headers": "^1.4.7",
    "gatsby-remark-images": "^1.5.10",
    "gatsby-remark-prismjs": "^1.2.7",
    "gatsby-source-filesystem": "^1.4.12",
    "gatsby-transformer-remark": "^1.7.7",
    "gatsby-transformer-yaml": "^1.5.7",
    "github-markdown-css": "^2.8.0",
    "grid-styled": "^2.0.0-10",
    "polished": "^1.7.0",
    "prop-types": "^15.5.10",
    "react-draggable": "^3.0.3",
    "react-headroom": "^2.1.6",
    "react-icons": "^2.2.5",
    "react-visibility-sensor": "^3.10.1",
    "styled-media-query": "^2.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "eslint": "^4.6.1",
    "eslint-config-prettier": "^2.4.0",
    "eslint-plugin-prettier": "^2.2.0",
    "eslint-plugin-react": "^7.3.0",
    "husky": "^0.14.3",
    "lint-staged": "^4.1.0",
    "prettier": "^1.6.1",
    "typescript": "^2.5.3",
    "typescript-styled-plugin": "^0.0.1"
  }
}
  ```
</details>

VS Code: `v1.16.1`

**Comment by mjbvz** [comment] 2017-10-15 20:40
@lyyourc Can you try VS Code 1.17 with the latest version of this plugin (0.1.0)? 

I've also created a simple example project that shows to use this plugin with vscode: https://github.com/mjbvz/typescript-styled-plugin-example-project

**Comment by lyyourc** [comment] 2017-10-16 03:07
It works now, great! @mjbvz

**Comment by mjbvz** [comment] 2017-10-16 17:45
The json schema should now be fixed by https://github.com/SchemaStore/schemastore/pull/348

If you are still seeing issues where the plugin is not being loaded in VSCode 1.17, please open a new issue

**Closed by mjbvz** 2017-10-16 17:45 UTC
