### ISSUE TITLE
Linting error for pseudo-classes

### ISSUE THREAD

**Issue by ibraback** [Microsoft/typescript-styled-plugin#13] opened 2017-10-08 00:21 UTC
Hello, I got this linting error in my VSCode editor specifically when I use CSS pseudo-classes in styled-components way (like hover in the screenshot below for example), I hope that this bug will be fixed soon to make this extension even better 🙂
 
![screenshot 54](https://user-images.githubusercontent.com/19997619/31312813-345122d4-abc6-11e7-83d3-212502f80740.png)

**Comment by mjbvz** [comment] 2017-10-08 13:23
Duplicate of #2

If this is getting in the way, you can disable linting by setting  `validate: false` https://github.com/Microsoft/typescript-styled-plugin#linting

**Closed by mjbvz** 2017-10-08 13:23 UTC
Labels: duplicate
